### ISSUE TITLE
Add website URL + description to github repo metadata

### ISSUE THREAD

**Issue by transitive-bullshit** [PineappleExpress808/besties-gpt#1]
Often overlooked but super important for devs to quickly check out your project :)

I didn't see https://besties-gpt.fly.dev prominently in the repo and was about to bounce cause I couldn't try it out but then saw it in your tweet.

Looks awesome && will give more feedback on twitter

**Comment by rlancemartin** [comment]
done! thanks for the call-out.

**Comment by transitive-bullshit** [comment]
awesome ;) for some reason, the link isn't clickable on github. no idea why though

<img width="327" alt="CleanShot 2023-03-29 at 18 45 49@2x" src="https://user-images.githubusercontent.com/552829/228692266-e21c3cba-a73d-4735-a8cc-31cbf182ec04.png">

**Comment by rlancemartin** [comment]
ah, strange. i think it is now!
